name: CI Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  backend:
    name: Backend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Archive backend coverage report
        uses: actions/upload-artifact@v3
        with:
         name: backend-coverage
         path: back/target/site/jacoco

  frontend:
    name: Frontend tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run frontend tests
        run: npm run test -- --watch=false --no-progress --browsers=ChromeHeadless --code-coverage

      - name: Archive frontend coverage report
        uses: actions/upload-artifact@v3
        with:
          name: frontend-coverage
          path: front/coverage
